language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
git:
  depth: 3
cache:
  directories:
    - $HOME/.pub-cache
env:
  - FLUTTER_VERSION=beta
  - FLUTTER_VERSION=dev
  - FLUTTER_VERSION=stable
matrix:
  allow_failures:
    - env: FLUTTER_VERSION=dev
    - env: FLUTTER_VERSION=beta
install:
  - cd ../
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
script:
  - cd Animated-Text-Kit/
  - ../flutter/bin/flutter test
  - ../flutter/bin/flutter analyze .
  - ../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run lib/
  - ../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run test/
  - ../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run example/lib/
