name: Deploy to Live Channel

on:
  push:
    branches:
      - master

jobs:
  live:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: animated-text-kit
          entryPoint: "./example"
          channelId: live
